### ISSUE TITLE
view location of undefined function

### ISSUE THREAD

**Issue by michield** [glenscott/php-dependencies#1]
I used your code, and found several functions undefined. It will be useful to find out where they are mentioned.

https://mantis.phplist.com/view.php?id=17560

**Comment by michield** [comment]
Ah, well, a simple grep finds them. 

In my case, not all are functions though. eg domain_batch_period is a constant.

**Comment by glenscott** [comment]
Hi Michiel,

Thanks for your comments.

I think a verbose mode that shows file and line number of functions and
classes would be useful.

I'll check to see why it has flagged a constant definition - this may be a
bug.

Glen

**Comment by michield** [comment]
Yes, I'll have a look if I can find the bug. Quite a few of my results are affected by it.

**Comment by michield** [comment]
The constants are found as functions on this line:

$running_throttle_delay = (int)(MAILQUEUE_THROTTLE + (DOMAIN_BATCH_PERIOD / (DOMAIN_BATCH_SIZE \* 4)));
